### ISSUE TITLE
Server Hang up with 1.16.5

### ISSUE THREAD

**Issue by Vaex** [DonovanDMC/ProjectExpansion#13] opened 2022-03-09 19:52 UTC
Hello DonovanDMC

I used your ProjectExpansion because the other one seems to be dead. My Client starts without problems but the Server hangs up.

My Version ist: [1.16.5]1.0.9

Crash Dump: [PasteBin](https://pastebin.com/iKAH5BWU)

**Comment by isaacrules2010** [comment] 2022-03-11 22:29
I am having the same issue... :( 

Something about "invalid dist DEDICATED_SERVER"

**Comment by DonovanDMC** [comment] 2022-03-11 23:59
This issue is coming about due to the way I wrote the mod, I'm in the process of moving and this will likely take a codebase rewrite so it's going to take some time to fix

**Comment by DonovanDMC** [comment] 2022-03-11 23:59
This issue is coming about due to the way I wrote the mod, I'm in the process of moving and this will likely take a codebase rewrite so it's going to take some time to fix

**Comment by Vaex** [comment] 2022-03-12 14:22
Alright @DonovanDMC i'm so happy for all your work you do. I have time to wait :) please keep it up, it's amazing.

**Comment by DonovanDMC** [comment] 2022-03-13 01:06
I've got a dev build (`1.16.5-1.0.10-dev.20220312`) that should fix this, if you guys could try it out that would be nice

I'm apparently not able to upload jar files here, and don't want to make a full release yet, so I'll just link to a [download](https://furry.cool/tmp/ProjectExpansion-1.16.5-1.0.10-dev.20220312.jar)

I'll make a release once this is confirmed fixed, and #14 is fixed

**Comment by Vaex** [comment] 2022-03-13 10:46
Thanks for your dev-build to test it out. My Server is now able to start without any Problems. I also test and check to verify #14 but when i place a Relay it crashes (could be a possible Problem with another mod?)

Here is another [PasteBin](https://pastebin.com/wrPUYKPc) related to #14

**Comment by DonovanDMC** [comment] 2022-03-13 11:05
Ah yeah that's probably a problem with the changes I made to tile entity registration, I'm going to assume it effects all blocks that have tile entities  - I'll have a fix cooked up for that here in a few hours

**Comment by Vaex** [comment] 2022-03-13 13:19
amazing i'm already hungry to taste the new fix :) 👍

**Comment by DonovanDMC** [comment] 2022-03-13 21:34
Well here's [another download](https://furry.cool/tmp/ProjectExpansion-1.16.5-1.0.10-dev.20220313a.jar) that fixes that tile entity issue, still haven't had the time to look into relays yet

**Comment by Vaex** [comment] 2022-03-13 23:30
i'm gonna check it out asap. No Problem Donovan, keep your time, it is a big change.

**Comment by Vaex** [comment] 2022-03-14 19:36
Okay it works, i can place tile entities.

**Comment by DonovanDMC** [comment] 2022-03-18 01:14
Fixed in 1.0.10 for 1.16, a fix for 1.15 is pending

[new release](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.10)

**Comment by Vaex** [comment] 2022-03-19 09:01
Thank you so much

**Comment by DonovanDMC** [comment] 2022-03-20 01:29
Backported to 1.15 in [[1.15] 1.0.11](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.11)

**Closed as completed by DonovanDMC** 2022-03-20 01:29 UTC
Labels: bug, Fixed, 1.16, 1.15
