### ISSUE TITLE
Crash when player dies while having a power flower

### ISSUE THREAD

**Issue by benediktwerner** [DonovanDMC/ProjectExpansion#52] opened 2022-06-02 12:25 UTC
Crash log: https://mclo.gs/VdK3Tjm

Had the server crash two times when a player died. The crash log seems to indicate it's caused by Project Expansion's power flowers. Not sure if it matters but the player has roughly a dozen final power flowers next to four watches of flowing time on dark matter pedestals and both times he was one-shot by another player. The server immediately crashed the moment they died and I don't think they died any other times since they built the power flowers.

**Comment by DonovanDMC** [comment] 2022-06-02 12:46
This looks like more of an issue with ProjectE, we're [calling methods](https://github.com/sinkillerj/ProjectE/blob/mc1.18.x/src/main/java/moze_intel/projecte/impl/TransmutationProxyImpl.java#L37) that should be safe. I can likely add a handler to catch this error and throw it away though

**Comment by DonovanDMC** [comment] 2022-06-02 13:11
Reproduced in 1.18, killed by player, zombie & lightning (all 3 crashed)

Can't reproduce in 1.14 & 1.15
<img src="https://user-images.githubusercontent.com/17226394/171635682-6eaed8b0-efdb-47fc-a48a-621c808f7b37.png" width="35%"><img src="https://user-images.githubusercontent.com/17226394/171635691-00db5e14-8721-4478-8265-2557b3619ad0.png" width="35%">

**Comment by border999** [comment] 2022-06-04 23:30
I can also attest to this issue. Died to radiation poisoning. Can no longer get into my world for the time being.
[crash-2022-06-04_19.25.39-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/8839089/crash-2022-06-04_19.25.39-server.txt)
Any ETA on a fix from ProjectExpansion or plain old ProjectE?

**Comment by DonovanDMC** [comment] 2022-06-05 03:29
Fixed in [1.0.6](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.6)

**Closed as completed by DonovanDMC** 2022-06-05 03:29 UTC
Labels: bug, 1.18, confirmed
