### ISSUE TITLE
Crash when requesting items with Pretty Pipes

### ISSUE THREAD

**Issue by HoodBlah** [DonovanDMC/ProjectExpansion#87] opened 2023-03-17 01:12 UTC
I made the Transmutation Link and connected it to my storage with pretty pipes. I decided to test it out by auto crafting a campfire. But once I pressed the request button to get the item my server crashed.

[debug.log](https://github.com/DonovanDMC/ProjectExpansion/files/10996919/debug.log)

**Comment by DonovanDMC** [comment] 2023-03-17 01:18
I'd prefer the actual crash report over your log files

**Comment by HoodBlah** [comment] 2023-03-17 01:22
[crash-2023-03-16_21.09.08-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/10996949/crash-2023-03-16_21.09.08-server.txt)

^^^ Here is the file from the crash report folder, below are the log and debug files i have from the crash incase you need them

[debug-1.log.gz](https://github.com/DonovanDMC/ProjectExpansion/files/10996972/debug-1.log.gz)
[2023-03-16-1.log.gz](https://github.com/DonovanDMC/ProjectExpansion/files/10996973/2023-03-16-1.log.gz)

**Comment by HoodBlah** [comment] 2023-03-17 01:25
Also, after getting back in the world the items I requested were inside the terminals recieve section and not the crafting section I requested them too.

**Comment by HoodBlah** [comment] 2023-03-17 01:26
putting items in is no issue tho

I tried requesting one item normally without using the crafter and it still crashed

[crash-2023-03-16_21.25.18-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/10997016/crash-2023-03-16_21.25.18-server.txt)

[debug.log](https://github.com/DonovanDMC/ProjectExpansion/files/10997020/debug.log)

[latest.log](https://github.com/DonovanDMC/ProjectExpansion/files/10997021/latest.log)

**Comment by DonovanDMC** [comment] 2023-03-17 01:33
This is happening due to the way they go about extracting items
it isn't necessarily wrong, but it's different that what most mods do

the issue is coming from us, but due to it being an incompatibility with one mod I'm not considering it a priority

**Comment by HoodBlah** [comment] 2023-03-17 01:36
alright, ios there an eta on a fix?

**Comment by DonovanDMC** [comment] 2023-03-17 01:37
no

**Comment by HoodBlah** [comment] 2023-03-27 21:14
Hi, just wanted too ask if a fix will come out for all versions or just one. Such as for 1.18.2 and 1.19.2, not only 1.18.2.

**Comment by HoodBlah** [comment] 2023-09-23 19:53
Hello, it’s been like half a year since this issue was made. Will it ever be fixed?

**Comment by DonovanDMC** [comment] 2023-09-23 20:27
There are many different things that are much higher priority than compatibility with a mod that's behaving in a nonstandard way

**Comment by HoodBlah** [comment] 2023-09-24 20:26
Alright then. Also, the retrieval module still works. So if I set a retrieval module from the link to a chest and set the module to request emerald, emerald will safely be travel from the link to the chest with no issue. The problem only happens when I use the pretty pipes terminals.

**Comment by HoodBlah** [comment] 2023-09-26 12:36
Ellpeck/PrettyPipes#192

**Comment by DonovanDMC** [comment] 2023-10-12 22:26
Fixed in [1.0.10](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.19.2-1.0.10) for 1.19.2

**Closed as completed by DonovanDMC** 2023-10-12 22:26 UTC
Labels: bug, non-priority, 1.19.2

**Comment by DonovanDMC** [comment] 2023-10-17 11:07
1.18: [1.0.21](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.21)
1.16: [1.0.41](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.41)
